development: &common
  # define migrations_path if you want to keep your migrations in a different folder
  # migrations_path: 'geoserver/migrate'
  api:
    base: "http://localhost:8080/geoserver/rest"
    user: admin
    password: geoserver

test:
  <<: *common   # merges key:value pairs defined in development anchor

production:
  <<: *common   # merges key:value pairs defined in development anchor